---
abstract: 'Run code blocks according to a given probability'
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Frequency
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
  Test::More: 0.9
  parent: 0
version: 0.05
