--- #YAML:1.0
name:               Sub-Frequency
version:            0.02
abstract:           Run code blocks according to a given probability
author:
    - Breno G. de Oliveira <garu@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    Exporter:      0
    parent:        0
    Scalar::Util:  0
    Test::More:    0.9
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
